# Generated by Django 3.0.6 on 2020-06-01 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('TeamID', models.IntegerField(primary_key=True, serialize=False)),
                ('TeamName', models.CharField(max_length=50)),
                ('TeamRank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('PID', models.IntegerField(primary_key=True, serialize=False)),
                ('PName', models.CharField(max_length=100)),
                ('PAge', models.IntegerField()),
                ('PType', models.CharField(max_length=150)),
                ('TeamID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Teams')),
            ],
        ),
    ]
