# Generated by Django 3.0.6 on 2020-06-03 15:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeamName', models.CharField(max_length=50)),
                ('TeamRank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SeriesName', models.CharField(max_length=100)),
                ('StartDate', models.DateField(blank=True, default=datetime.datetime.now)),
                ('EndDate', models.DateField(blank=True, default=datetime.datetime.now)),
                ('Teams', models.ManyToManyField(to='teams.Teams')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PName', models.CharField(max_length=100)),
                ('PAge', models.IntegerField()),
                ('PType', models.CharField(max_length=150)),
                ('Team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Teams')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Series_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Series')),
                ('Teams', models.ManyToManyField(to='teams.Teams')),
            ],
        ),
    ]
