# Generated by Django 3.0.6 on 2020-06-02 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='SeriesID',
        ),
        migrations.AddField(
            model_name='match',
            name='Series_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='teams.Series'),
            preserve_default=False,
        ),
    ]
