# Generated by Django 3.0.6 on 2020-06-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20200606_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='MatchDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='Points',
            field=models.IntegerField(default=0),
        ),
    ]
