# Generated by Django 3.0.6 on 2020-06-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20200606_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='MatchDecided',
            field=models.BooleanField(default=False),
        ),
    ]
