# Generated by Django 3.0.6 on 2020-06-02 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_mteams_steams'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mteams',
        ),
        migrations.DeleteModel(
            name='STeams',
        ),
    ]
