# Generated by Django 3.0.6 on 2020-06-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_match_matchdecided'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='MatchDecided',
        ),
        migrations.AddField(
            model_name='match',
            name='WinningTeam',
            field=models.CharField(default='NoTeam', max_length=100),
        ),
    ]
