# Generated by Django 3.0.6 on 2020-06-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_auto_20200607_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='Teams',
            field=models.ManyToManyField(to='teams.Teams'),
        ),
        migrations.AlterField(
            model_name='series',
            name='Teams',
            field=models.ManyToManyField(to='teams.Teams'),
        ),
    ]
